# Generated by Django 4.0.4 on 2022-05-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='uploadedFile',
            field=models.ImageField(upload_to='Uploaded Files/'),
        ),
    ]
