# Generated by Django 4.0.4 on 2022-05-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_image_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='uploadedFile',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='image',
            name='dateTimeOfUpload',
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(default='None', max_length=600),
        ),
    ]
