# Generated by Django 4.0.4 on 2022-05-18 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_image_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Upload',
        ),
    ]
