# Generated by Django 4.0.4 on 2022-05-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_upload_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='img',
            field=models.ImageField(default='', upload_to='Uploaded Files/'),
        ),
    ]
