# Generated by Django 4.0.4 on 2022-05-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_upload_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='img',
            field=models.ImageField(blank=True, default='None', null=True, upload_to='Uploaded Files/'),
        ),
    ]
