# Generated by Django 4.0.4 on 2022-05-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_upload_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='description',
            field=models.CharField(blank=True, default='-', max_length=600, null=True),
        ),
    ]
