# Generated by Django 4.0.4 on 2022-06-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_upload_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='description',
            field=models.CharField(blank=True, default='/', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='img',
            field=models.ImageField(blank=True, default='Empty', upload_to='Uploaded Files/'),
        ),
    ]
